Repository aws-controllers-k8s/elasticache-controller, pull requests merged in 2021-07, with the labels that each got.

#31 SDK update to v1.38.52 to add LogDelivery support
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/cache_parameter_group.go
  apis/v1alpha1/enums.go
  apis/v1alpha1/replication_group.go
  apis/v1alpha1/snapshot.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_snapshots.yaml
  generator.yaml
  go.mod
  go.sum
  pkg/resource/cache_parameter_group/resource.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/resource.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/custom_set_output.go
  pkg/resource/replication_group/delta.go
  pkg/resource/replication_group/resource.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/snapshot/resource.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/resource.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/resource.go
  pkg/resource/user_group/sdk.go
  templates/hooks/sdk_update_post_build_request.go.tpl
  test/e2e/bootstrap_resources.py
  test/e2e/resources/replicationgroup_input_coverage.yaml
  test/e2e/service_bootstrap.py
  test/e2e/service_cleanup.py
  test/e2e/tests/test_replicationgroup.py
Labels: approved, ok-to-test

#38 regenerate code
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  config/crd/common/bases/services.k8s.aws_adoptedresources.yaml
  pkg/resource/cache_parameter_group/manager.go
  pkg/resource/cache_parameter_group/manager_factory.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/manager.go
  pkg/resource/cache_subnet_group/manager_factory.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/manager.go
  pkg/resource/replication_group/manager_factory.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/snapshot/manager.go
  pkg/resource/snapshot/manager_factory.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/manager.go
  pkg/resource/user/manager_factory.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/manager.go
  pkg/resource/user_group/manager_factory.go
  pkg/resource/user_group/sdk.go
Labels: approved

#39 Enable Passwords field (upon creation)
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/user.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elasticache.services.k8s.aws_users.yaml
  generator.yaml
  pkg/resource/user/post_build_request.go
  pkg/resource/user/sdk.go
  test/e2e/resources/user_nopass.yaml
  test/e2e/resources/user_password.yaml
  test/e2e/tests/test_replicationgroup.py
  test/e2e/tests/test_user.py
Labels: approved

#41 fix deletion assertions in user e2e tests
  test/e2e/tests/test_user.py
  test/e2e/util.py
Labels: approved

#42 regenerate code, fix replication group delete templates, upgrade to runtime 0.6.0
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  cmd/controller/main.go
  go.mod
  go.sum
  pkg/resource/cache_parameter_group/manager.go
  pkg/resource/cache_parameter_group/resource.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/manager.go
  pkg/resource/cache_subnet_group/resource.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/manager.go
  pkg/resource/replication_group/resource.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/replication_group/testdata/test_suite.yaml
  pkg/resource/snapshot/manager.go
  pkg/resource/snapshot/resource.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/manager.go
  pkg/resource/user/resource.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/manager.go
  pkg/resource/user_group/resource.go
  pkg/resource/user_group/sdk.go
  pkg/testutil/test_suite_runner.go
  templates/hooks/sdk_delete_post_request.go.tpl
  templates/hooks/sdk_delete_pre_build_request.go.tpl
Labels: approved

#36 Auto generate setoutput method and use it from custom code
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/replication_group/custom_set_output.go
  pkg/resource/replication_group/custom_update_api.go
  pkg/resource/replication_group/delta_util.go
  pkg/resource/replication_group/post_set_output.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_engine_version_upgrade.yaml
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_engine_version_upgrade_latest.yaml
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_increase_replica.yaml
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_increase_replica_latest.yaml
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_engine_upgrade_initiated.yaml
  pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_increase_replica_initiated.yaml
  pkg/resource/replication_group/testdata/replication_group/update/rg_cmd_engine_upgrade_initiated.json
  pkg/resource/replication_group/testdata/replication_group/update/rg_cmd_increase_replica_initiated.json
  templates/hooks/sdk_delete_post_request.go.tpl
  templates/hooks/sdk_file_end.go.tpl
Labels: approved

#44 Add service metadata file
  metadata.yaml
Labels: approved, lgtm

#46 ElastiCache Fixes with new code generator
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/cache_parameter_group.go
  apis/v1alpha1/cache_subnet_group.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/replication_group.go
  apis/v1alpha1/snapshot.go
  apis/v1alpha1/user.go
  apis/v1alpha1/user_group.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_snapshots.yaml
  config/crd/bases/elasticache.services.k8s.aws_usergroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_users.yaml
  generator.yaml
  go.mod
  go.sum
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/custom_update_api.go
  pkg/resource/replication_group/delta.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/sdk.go
  test/e2e/resources/replicationgroup_cmd_fromsnapshot.yaml
Labels: approved

#45 add test for cpg update, refactor e2e tests
  test/e2e/bootstrap_resources.py
  test/e2e/service_bootstrap.py
  test/e2e/service_cleanup.py
  test/e2e/tests/test_replicationgroup.py
Labels: approved
