Repository aws-controllers-k8s/elasticache-controller, pull requests merged in 2021-09, with the labels that each got.

#53 support Tags field for all resources (on create)
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/cache_parameter_group.go
  apis/v1alpha1/cache_subnet_group.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/replication_group.go
  apis/v1alpha1/snapshot.go
  apis/v1alpha1/user.go
  apis/v1alpha1/user_group.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_snapshots.yaml
  config/crd/bases/elasticache.services.k8s.aws_usergroups.yaml
  config/crd/bases/elasticache.services.k8s.aws_users.yaml
  generator.yaml
  helm/crds/elasticache.services.k8s.aws_cacheparametergroups.yaml
  helm/crds/elasticache.services.k8s.aws_cachesubnetgroups.yaml
  helm/crds/elasticache.services.k8s.aws_replicationgroups.yaml
  helm/crds/elasticache.services.k8s.aws_snapshots.yaml
  helm/crds/elasticache.services.k8s.aws_usergroups.yaml
  helm/crds/elasticache.services.k8s.aws_users.yaml
  pkg/resource/cache_parameter_group/delta.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/delta.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/delta.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/snapshot/delta.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/delta.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/delta.go
  pkg/resource/user_group/sdk.go
Labels: approved

#56 standardize setting conditions on RGs
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  go.mod
  go.sum
  helm/templates/deployment.yaml
  helm/values.yaml
  pkg/resource/cache_parameter_group/manager.go
  pkg/resource/cache_parameter_group/resource.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/manager.go
  pkg/resource/cache_subnet_group/resource.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/custom_set_conditions.go
  pkg/resource/replication_group/hooks.go
  pkg/resource/replication_group/manager.go
  pkg/resource/replication_group/resource.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/replication_group/testdata/test_suite.yaml
  pkg/resource/snapshot/manager.go
  pkg/resource/snapshot/resource.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/manager.go
  pkg/resource/user/resource.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/manager.go
  pkg/resource/user_group/resource.go
  pkg/resource/user_group/sdk.go
  templates/hooks/replication_group/sdk_delete_post_request.go.tpl
  templates/hooks/replication_group/sdk_delete_pre_build_request.go.tpl
  templates/hooks/replication_group/sdk_file_end.go.tpl
  templates/hooks/replication_group/sdk_read_many_post_set_output.go.tpl
  templates/hooks/replication_group/sdk_update_post_build_request.go.tpl
  templates/hooks/sdk_delete_post_request.go.tpl
  templates/hooks/sdk_delete_pre_build_request.go.tpl
Labels: approved

#55 bring in ACK runtime v0.13.2
  apis/v1alpha1/ack-generate-metadata.yaml
  go.mod
  go.sum
  helm/templates/deployment.yaml
  helm/values.yaml
  pkg/resource/cache_parameter_group/manager.go
  pkg/resource/cache_parameter_group/resource.go
  pkg/resource/cache_parameter_group/sdk.go
  pkg/resource/cache_subnet_group/manager.go
  pkg/resource/cache_subnet_group/resource.go
  pkg/resource/cache_subnet_group/sdk.go
  pkg/resource/replication_group/manager.go
  pkg/resource/replication_group/resource.go
  pkg/resource/replication_group/sdk.go
  pkg/resource/snapshot/manager.go
  pkg/resource/snapshot/resource.go
  pkg/resource/snapshot/sdk.go
  pkg/resource/user/manager.go
  pkg/resource/user/resource.go
  pkg/resource/user/sdk.go
  pkg/resource/user_group/manager.go
  pkg/resource/user_group/resource.go
  pkg/resource/user_group/sdk.go
Labels: approved, lgtm

#54 release artifacts for release v0.0.5
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  helm/Chart.yaml
  helm/values.yaml
Labels: approved, lgtm

#49 e2e tests to cover most replication group update scenarios
  test/e2e/bootstrap_resources.py
  test/e2e/resources/replicationgroup_cme_misc.yaml
  test/e2e/resources/replicationgroup_cme_ngc.yaml
  test/e2e/resources/replicationgroup_fault_tolerance.yaml
  test/e2e/resources/replicationgroup_primary_cluster.yaml
  test/e2e/resources/replicationgroup_rpng.yaml
  test/e2e/service_bootstrap.py
  test/e2e/service_cleanup.py
  test/e2e/tests/test_replicationgroup.py
  test/e2e/util.py
Labels: approved

#58 Add CacheClusterNotFound terminal code
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  helm/templates/metrics-service.yaml
  pkg/resource/replication_group/sdk.go
  test/e2e/tests/test_replicationgroup.py
Labels: approved

#61 Enable Scale-In without NodeGroupConfiguration
  pkg/resource/replication_group/custom_update_api.go
Labels: needs-ok-to-test
